### ISSUE TITLE
 Project Hydroflow not found 

### ISSUE THREAD

**Issue by zzl221000** [hydro-project/hydroflow-template#1]
Why was hydroflow removed? I was just about to give it a try.

**Comment by MingweiSamuel** [comment]
So we, uhh, accidentally deleted the repository. Working with github to get it back up, sorry for the trouble.
Copy of the repo is available here: https://github.com/MingweiSamuel/hydroflow-backup

**Comment by MingweiSamuel** [comment]
book: https://www.mingweisamuel.com/hydroflow-backup/book/

rustdocs: https://www.mingweisamuel.com/hydroflow-backup/doc/hydroflow_lang/index.html

**Comment by MingweiSamuel** [comment]
main repo is back up!
https://github.com/hydro-project/hydroflow
https://hydro-project.github.io/hydroflow/
