### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by FranklinChen** [hydro-project/hydroflow-template#2]
```
$ cargo build
...
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/chen/.cargo/git/checkouts/hydroflow-bd9de84a73a76f97/4b3233a/hydroflow_internalmacro/src/lib.rs:1:12
  |
1 | #![feature(proc_macro_diagnostic, proc_macro_span)]
  |            ^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/chen/.cargo/git/checkouts/hydroflow-bd9de84a73a76f97/4b3233a/hydroflow_internalmacro/src/lib.rs:1:35
  |
1 | #![feature(proc_macro_diagnostic, proc_macro_span)]
  |                                   ^^^^^^^^^^^^^^^

```

Perhaps add GitHub Actions for this template to ensure that it builds?

**Comment by MingweiSamuel** [comment]
Hydroflow requires the nightly release channel. I'm not sure why `cargo build` isn't using nightly even though the toolchain file specifies it
https://github.com/hydro-project/hydroflow-template/blob/2f1fefe6640cb24856637a78b9500482016d17fd/rust-toolchain.toml#L1-L2

**Comment by FranklinChen** [comment]
Exactly, I don't know why either.

**Comment by FranklinChen** [comment]
Ugh, I found the problem. I'm on macOS and somehow had the `rust` formula installed, resulting in `cargo` being in my path that was not the `rustup` version of `cargo` I was supposed to be using, so `rust-toolchain.toml` was not being respected.
